/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bloodtestscheduler;

/**
 *
 * @author Leandro
 */
public class BloodTestSchedulerGUI extends javax.swing.JFrame {

    /**
     * Creates new form BloodTestSchedulerGUI
     */
    public BloodTestSchedulerGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        appTitleLabel = new javax.swing.JLabel();
        patientNameTextFieldLabel = new javax.swing.JLabel();
        patientNameTextField = new javax.swing.JTextField();
        patientAgeTextFieldLabel = new javax.swing.JLabel();
        patientAgeTextField = new javax.swing.JTextField();
        patientGPNameFieldLabel = new javax.swing.JLabel();
        patientGPNameField = new javax.swing.JTextField();
        patientGPLicenseFieldLabel = new javax.swing.JLabel();
        patientGPLicenseField = new javax.swing.JTextField();
        patientPriorityButtonGroupLabel = new javax.swing.JLabel();
        patientPriorityButtonHigh = new javax.swing.JRadioButton();
        patientPriorityButtonMedium = new javax.swing.JRadioButton();
        patientPriorityButtonLow = new javax.swing.JRadioButton();
        patientOriginCheckBoxLabel = new javax.swing.JLabel();
        patientOriginCheckBox = new javax.swing.JCheckBox();
        addPatientButton = new javax.swing.JButton();
        processNextPatientButton = new javax.swing.JButton();
        markPatientNoShowButton = new javax.swing.JButton();
        patientsQueueListTextAreaLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        patientsQueueListTextArea = new javax.swing.JTextArea();
        patientsNoShowListLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        patientsNoShowList = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        appTitleLabel.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 1, 36)); // NOI18N
        appTitleLabel.setText("Blood Test Scheduler");

        patientNameTextFieldLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        patientNameTextFieldLabel.setText("Patient full name");

        patientAgeTextFieldLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        patientAgeTextFieldLabel.setText("Patient age");

        patientGPNameFieldLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        patientGPNameFieldLabel.setText("GP full name");

        patientGPLicenseFieldLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        patientGPLicenseFieldLabel.setText("GP license number");

        patientPriorityButtonGroupLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        patientPriorityButtonGroupLabel.setText("Priority");

        buttonGroup1.add(patientPriorityButtonHigh);
        patientPriorityButtonHigh.setText("High");
        patientPriorityButtonHigh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientPriorityButtonHighActionPerformed(evt);
            }
        });

        buttonGroup1.add(patientPriorityButtonMedium);
        patientPriorityButtonMedium.setText("Medium");
        patientPriorityButtonMedium.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientPriorityButtonMediumActionPerformed(evt);
            }
        });

        buttonGroup1.add(patientPriorityButtonLow);
        patientPriorityButtonLow.setText("Low");
        patientPriorityButtonLow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientPriorityButtonLowActionPerformed(evt);
            }
        });

        patientOriginCheckBoxLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        patientOriginCheckBoxLabel.setText("Patient origin");

        patientOriginCheckBox.setText("Patient from Hospital Ward");
        patientOriginCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientOriginCheckBoxActionPerformed(evt);
            }
        });

        addPatientButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        addPatientButton.setText("Add patient");
        addPatientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPatientButtonActionPerformed(evt);
            }
        });

        processNextPatientButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        processNextPatientButton.setText("Process next");
        processNextPatientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processNextPatientButtonActionPerformed(evt);
            }
        });

        markPatientNoShowButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        markPatientNoShowButton.setText("Mark No Show");

        patientsQueueListTextAreaLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        patientsQueueListTextAreaLabel.setText("Current patients queue status");

        patientsQueueListTextArea.setColumns(20);
        patientsQueueListTextArea.setRows(5);
        jScrollPane1.setViewportView(patientsQueueListTextArea);

        patientsNoShowListLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        patientsNoShowListLabel.setText("Last no-shows");

        jScrollPane2.setViewportView(patientsNoShowList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(patientOriginCheckBox)
                            .addComponent(patientPriorityButtonGroupLabel)
                            .addComponent(patientGPNameFieldLabel)
                            .addComponent(patientAgeTextFieldLabel)
                            .addComponent(patientGPLicenseFieldLabel)
                            .addComponent(patientNameTextFieldLabel)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(appTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(patientGPLicenseField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(patientGPNameField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(patientAgeTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(patientNameTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(39, 39, 39)
                                        .addComponent(addPatientButton, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(processNextPatientButton, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(50, 50, 50))))
                            .addComponent(patientOriginCheckBoxLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(patientPriorityButtonHigh)
                                .addGap(18, 18, 18)
                                .addComponent(patientPriorityButtonMedium)
                                .addGap(18, 18, 18)
                                .addComponent(patientPriorityButtonLow)))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(markPatientNoShowButton, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(134, 134, 134)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(patientsQueueListTextAreaLabel)
                    .addComponent(patientsNoShowListLabel)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(appTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientNameTextFieldLabel)
                    .addComponent(patientsQueueListTextAreaLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(patientNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(patientAgeTextFieldLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(patientAgeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(patientGPNameFieldLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(patientGPNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(patientGPLicenseFieldLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(patientGPLicenseField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(patientPriorityButtonGroupLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(patientPriorityButtonHigh)
                            .addComponent(patientPriorityButtonMedium)
                            .addComponent(patientPriorityButtonLow)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientOriginCheckBoxLabel)
                    .addComponent(patientsNoShowListLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(patientOriginCheckBox)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addPatientButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(processNextPatientButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(markPatientNoShowButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void patientPriorityButtonHighActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientPriorityButtonHighActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patientPriorityButtonHighActionPerformed

    private void patientOriginCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientOriginCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patientOriginCheckBoxActionPerformed

    private void addPatientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPatientButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addPatientButtonActionPerformed

    private void processNextPatientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processNextPatientButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_processNextPatientButtonActionPerformed

    private void patientPriorityButtonMediumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientPriorityButtonMediumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patientPriorityButtonMediumActionPerformed

    private void patientPriorityButtonLowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientPriorityButtonLowActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patientPriorityButtonLowActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BloodTestSchedulerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BloodTestSchedulerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BloodTestSchedulerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BloodTestSchedulerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BloodTestSchedulerGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addPatientButton;
    private javax.swing.JLabel appTitleLabel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton markPatientNoShowButton;
    private javax.swing.JTextField patientAgeTextField;
    private javax.swing.JLabel patientAgeTextFieldLabel;
    private javax.swing.JTextField patientGPLicenseField;
    private javax.swing.JLabel patientGPLicenseFieldLabel;
    private javax.swing.JTextField patientGPNameField;
    private javax.swing.JLabel patientGPNameFieldLabel;
    private javax.swing.JTextField patientNameTextField;
    private javax.swing.JLabel patientNameTextFieldLabel;
    private javax.swing.JCheckBox patientOriginCheckBox;
    private javax.swing.JLabel patientOriginCheckBoxLabel;
    private javax.swing.JLabel patientPriorityButtonGroupLabel;
    private javax.swing.JRadioButton patientPriorityButtonHigh;
    private javax.swing.JRadioButton patientPriorityButtonLow;
    private javax.swing.JRadioButton patientPriorityButtonMedium;
    private javax.swing.JList<String> patientsNoShowList;
    private javax.swing.JLabel patientsNoShowListLabel;
    private javax.swing.JTextArea patientsQueueListTextArea;
    private javax.swing.JLabel patientsQueueListTextAreaLabel;
    private javax.swing.JButton processNextPatientButton;
    // End of variables declaration//GEN-END:variables
}
