/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bloodtestscheduler;

import javax.swing.JOptionPane;

/**
 *
 * @author Leandro
 */
public class BloodTestSchedulerGUI extends javax.swing.JFrame {
    private final SchedulerService scheduler = new SchedulerService();
    
    /**
     * Creates new form BloodTestSchedulerGUI
     */
    public BloodTestSchedulerGUI() {
        initComponents();
        patientsQueueListTextArea.setContentType("text/html");
        patientsNoShowListTextArea.setContentType("text/html");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        appTitleLabel = new javax.swing.JLabel();
        patientNameTextFieldLabel = new javax.swing.JLabel();
        patientNameTextField = new javax.swing.JTextField();
        patientAgeTextFieldLabel = new javax.swing.JLabel();
        patientAgeTextField = new javax.swing.JTextField();
        patientGPNameFieldLabel = new javax.swing.JLabel();
        patientGPNameField = new javax.swing.JTextField();
        patientGPLicenseFieldLabel = new javax.swing.JLabel();
        patientGPLicenseField = new javax.swing.JTextField();
        patientPriorityButtonGroupLabel = new javax.swing.JLabel();
        patientPriorityButtonHigh = new javax.swing.JRadioButton();
        patientPriorityButtonMedium = new javax.swing.JRadioButton();
        patientPriorityButtonLow = new javax.swing.JRadioButton();
        patientOriginCheckBoxLabel = new javax.swing.JLabel();
        patientOriginCheckBox = new javax.swing.JCheckBox();
        addPatientButton = new javax.swing.JButton();
        processNextPatientButton = new javax.swing.JButton();
        markPatientNoShowButton = new javax.swing.JButton();
        patientsQueueListTextAreaLabel = new javax.swing.JLabel();
        patientsNoShowListLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        patientsQueueListTextArea = new javax.swing.JEditorPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        patientsNoShowListTextArea = new javax.swing.JEditorPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        appTitleLabel.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 1, 36)); // NOI18N
        appTitleLabel.setText("Blood Test Scheduler");

        patientNameTextFieldLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        patientNameTextFieldLabel.setText("Patient full name");

        patientAgeTextFieldLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        patientAgeTextFieldLabel.setText("Patient age");

        patientGPNameFieldLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        patientGPNameFieldLabel.setText("GP full name");

        patientGPLicenseFieldLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        patientGPLicenseFieldLabel.setText("GP license number");

        patientPriorityButtonGroupLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        patientPriorityButtonGroupLabel.setText("Priority");

        buttonGroup1.add(patientPriorityButtonHigh);
        patientPriorityButtonHigh.setText("High");
        patientPriorityButtonHigh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientPriorityButtonHighActionPerformed(evt);
            }
        });

        buttonGroup1.add(patientPriorityButtonMedium);
        patientPriorityButtonMedium.setText("Medium");
        patientPriorityButtonMedium.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientPriorityButtonMediumActionPerformed(evt);
            }
        });

        buttonGroup1.add(patientPriorityButtonLow);
        patientPriorityButtonLow.setText("Low");
        patientPriorityButtonLow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientPriorityButtonLowActionPerformed(evt);
            }
        });

        patientOriginCheckBoxLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        patientOriginCheckBoxLabel.setText("Patient origin");

        patientOriginCheckBox.setText("Patient from Hospital Ward");
        patientOriginCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientOriginCheckBoxActionPerformed(evt);
            }
        });

        addPatientButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        addPatientButton.setText("Add patient");
        addPatientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPatientButtonActionPerformed(evt);
            }
        });

        processNextPatientButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        processNextPatientButton.setText("Process next");
        processNextPatientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processNextPatientButtonActionPerformed(evt);
            }
        });

        markPatientNoShowButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        markPatientNoShowButton.setText("Mark No Show");
        markPatientNoShowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                markPatientNoShowButtonActionPerformed(evt);
            }
        });

        patientsQueueListTextAreaLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        patientsQueueListTextAreaLabel.setText("Current patients queue status");

        patientsNoShowListLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        patientsNoShowListLabel.setText("Last no-shows");

        jScrollPane2.setViewportView(patientsQueueListTextArea);

        jScrollPane1.setViewportView(patientsNoShowListTextArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(patientOriginCheckBox)
                            .addComponent(patientPriorityButtonGroupLabel)
                            .addComponent(patientGPNameFieldLabel)
                            .addComponent(patientAgeTextFieldLabel)
                            .addComponent(patientGPLicenseFieldLabel)
                            .addComponent(patientNameTextFieldLabel)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(appTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(patientGPLicenseField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(patientGPNameField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(patientAgeTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(patientNameTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(39, 39, 39)
                                        .addComponent(addPatientButton, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(processNextPatientButton, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(50, 50, 50))))
                            .addComponent(patientOriginCheckBoxLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(patientPriorityButtonHigh)
                                .addGap(18, 18, 18)
                                .addComponent(patientPriorityButtonMedium)
                                .addGap(18, 18, 18)
                                .addComponent(patientPriorityButtonLow)))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(markPatientNoShowButton, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(134, 134, 134)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(patientsQueueListTextAreaLabel)
                    .addComponent(patientsNoShowListLabel)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(appTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(patientNameTextFieldLabel)
                            .addComponent(patientsQueueListTextAreaLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(patientNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(patientAgeTextFieldLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(patientAgeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16)
                                .addComponent(patientGPNameFieldLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(patientGPNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(patientGPLicenseFieldLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(patientGPLicenseField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(patientPriorityButtonGroupLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(patientPriorityButtonHigh)
                                    .addComponent(patientPriorityButtonMedium)
                                    .addComponent(patientPriorityButtonLow)))
                            .addComponent(jScrollPane2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(patientOriginCheckBoxLabel)
                            .addComponent(patientsNoShowListLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(patientOriginCheckBox)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addPatientButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(processNextPatientButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addComponent(markPatientNoShowButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 25, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(333, 333, 333)
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void patientPriorityButtonHighActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientPriorityButtonHighActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patientPriorityButtonHighActionPerformed

    private void patientOriginCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientOriginCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patientOriginCheckBoxActionPerformed

    private void addPatientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPatientButtonActionPerformed
        try {
            String name = patientNameTextField.getText().trim();
            int age = Integer.parseInt(patientAgeTextField.getText().trim());
            String gpName = patientGPNameField.getText().trim();
            String gpLicense = patientGPLicenseField.getText().trim();
            String priority = patientPriorityButtonHigh.isSelected() ? "High" :
                            patientPriorityButtonMedium.isSelected() ? "Medium" : "Low";
            boolean fromHospital = patientOriginCheckBox.isSelected();

            if (name.isEmpty() || gpName.isEmpty() || gpLicense.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please fill all fields", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            Patient patient = new Patient(name, age, gpName, gpLicense, priority, fromHospital);
            scheduler.addPatient(patient);
            updateDisplay(); // custom method to genereate the HTML table for display
            clearForm();  // custom method to clean all the fields
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Please enter a valid age", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_addPatientButtonActionPerformed

    private void processNextPatientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processNextPatientButtonActionPerformed
    if (scheduler.isQueueEmpty()) {
        JOptionPane.showMessageDialog(this, "No patients in queue", "Info", JOptionPane.INFORMATION_MESSAGE);
        return;
    }
    Patient nextPatient = scheduler.processNextPatient();
    
    JOptionPane.showMessageDialog(this, 
        "Processing: " + nextPatient.getName(), 
        "Next Patient", 
        JOptionPane.INFORMATION_MESSAGE);
    updateDisplay();
    }//GEN-LAST:event_processNextPatientButtonActionPerformed

    private void patientPriorityButtonMediumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientPriorityButtonMediumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patientPriorityButtonMediumActionPerformed

    private void patientPriorityButtonLowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientPriorityButtonLowActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patientPriorityButtonLowActionPerformed

    private void markPatientNoShowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_markPatientNoShowButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_markPatientNoShowButtonActionPerformed

    private void updateDisplay() {      
        String listHeader = "<table>"+
                                "<tr>" +
                                    "<th>NAME</th>"+
                                    "<th>AGE</th>"+
                                    "<th>GP NAME</th>"+
                                    "<th>GP LICENSE</th>"+
                                    "<th>PRIORITY</th>"+
                                    "<th>FROM HOSPITAL WARD</th>"+
                                "</tr>";
        
        String listContent = "";
        String noShowListContent = "";
        
        String listEnd = "</table>";
        
        // Update queue display
        for (Patient p : scheduler.getQueueStatus()) {
            listContent += p.toString();
        }
        patientsQueueListTextArea.setText(listHeader + listContent + listEnd);

        // Update no-show list
        for (Patient p : scheduler.getNoShowsStatus()) {
            noShowListContent += p.toString();
        }
        patientsNoShowListTextArea.setText(listHeader + noShowListContent + listEnd);
    }

    private void clearForm() {
        patientNameTextField.setText("");
        patientAgeTextField.setText("");
        patientGPNameField.setText("");
        patientGPLicenseField.setText("");
        patientPriorityButtonMedium.setSelected(true);
        patientOriginCheckBox.setSelected(false);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addPatientButton;
    private javax.swing.JLabel appTitleLabel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton markPatientNoShowButton;
    private javax.swing.JTextField patientAgeTextField;
    private javax.swing.JLabel patientAgeTextFieldLabel;
    private javax.swing.JTextField patientGPLicenseField;
    private javax.swing.JLabel patientGPLicenseFieldLabel;
    private javax.swing.JTextField patientGPNameField;
    private javax.swing.JLabel patientGPNameFieldLabel;
    private javax.swing.JTextField patientNameTextField;
    private javax.swing.JLabel patientNameTextFieldLabel;
    private javax.swing.JCheckBox patientOriginCheckBox;
    private javax.swing.JLabel patientOriginCheckBoxLabel;
    private javax.swing.JLabel patientPriorityButtonGroupLabel;
    private javax.swing.JRadioButton patientPriorityButtonHigh;
    private javax.swing.JRadioButton patientPriorityButtonLow;
    private javax.swing.JRadioButton patientPriorityButtonMedium;
    private javax.swing.JLabel patientsNoShowListLabel;
    private javax.swing.JEditorPane patientsNoShowListTextArea;
    private javax.swing.JEditorPane patientsQueueListTextArea;
    private javax.swing.JLabel patientsQueueListTextAreaLabel;
    private javax.swing.JButton processNextPatientButton;
    // End of variables declaration//GEN-END:variables
}
